import 'package:flutter/material.dart';

class Autogenerated {
  List<Array>? array;
  int? totalContributions;
  int? weeklyContributionsSum;
  List<int>? weeklyContributions;
  int? dailyContributions;

  Autogenerated(
      {this.array,
      this.totalContributions,
      this.weeklyContributionsSum,
      this.weeklyContributions,
      this.dailyContributions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['array'] != null) {
      array = <Array>[];
      json['array'].forEach((v) {
        array!.add(new Array.fromJson(v));
      });
    }
    totalContributions = json['totalContributions'];
    weeklyContributionsSum = json['weeklyContributionsSum'];
    weeklyContributions = json['weeklyContributions'].cast<int>();
    dailyContributions = json['dailyContributions'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.array != null) {
      data['array'] = this.array!.map((v) => v.toJson()).toList();
    }
    data['totalContributions'] = this.totalContributions;
    data['weeklyContributionsSum'] = this.weeklyContributionsSum;
    data['weeklyContributions'] = this.weeklyContributions;
    data['dailyContributions'] = this.dailyContributions;
    return data;
  }
}

class Array {
  String? username;
  int? totalContributions;
  List<int>? weeklyContributions;
  int? weeklyContributionsSum;
  int? dailyContributions;

  Array(
      {this.username,
      this.totalContributions,
      this.weeklyContributions,
      this.weeklyContributionsSum,
      this.dailyContributions});

  Array.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    totalContributions = json['totalContributions'];
    weeklyContributions = json['weeklyContributions'].cast<int>();
    weeklyContributionsSum = json['weeklyContributionsSum'];
    dailyContributions = json['dailyContributions'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['username'] = this.username;
    data['totalContributions'] = this.totalContributions;
    data['weeklyContributions'] = this.weeklyContributions;
    data['weeklyContributionsSum'] = this.weeklyContributionsSum;
    data['dailyContributions'] = this.dailyContributions;
    return data;
  }
}
